[package]
name = "rusty-ircd"
version = "0.2.0"
authors = ["aoei /Joanna <jjadoyle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = [ "full" ] }
dns-lookup = "1.0"
