[package]
name = "irc_daemon"
version = "0.1.0"
authors = ["demo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.1"
futures = "0.1"
mio = "0.6"
